spring:
   datasource:
      username: equipment
      password: equipment
      url: jdbc:mysql://localhost:3306/equipment_management
      
      
   jpa:
         hibernate:
         ddl-auto: update
         show sql: true
